openapi: 3.0.0
info:
  title: Chatbot LLM Proxy API
  version: 1.0.0
  description: API BFF/Proxy para chatbot con JWT + seguridad completa

servers:
  - url: /

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: Auth
    description: Autenticación JWT
  - name: Chat
    description: Chatbot LLM

paths:
  /api/health:
    get:
      summary: Health check
      tags: [Health]
      responses: { '200': { description: 'OK' } }

  /api/auth/login:
    post:
      summary: Login demo (requiere API key)
      tags: [Auth]
      parameters:
        - name: demo-api-key
          in: header
          required: true
          schema: { type: string }
          description: "Clave demo autoriza webinar-front"
      responses:
        '200':
          description: JWT para webinar-front
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: { type: string }
                  expiresIn: { type: string }
        '401': { description: 'API key inválida' }

  /api/chat:
    post:
      summary: Chatbot LLM (requiere JWT)
      tags: [Chat]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message]
              properties:
                message: { type: string, example: "Hola" }
      responses:
        '200': { description: 'OK' }
        '401': { description: 'Unauthorized' }
